name: Build and Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'
    - run: julia -e '
        using Pkg; Pkg.activate("."); Pkg.instantiate();
        using NodeJS;
        run(`sudo $(npm_cmd()) install highlight.js`);
        using Franklin; 
        optimize()'
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        folder: __site

